# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "prosto_cache"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Olek Poplavsky"]
  s.date = "2012-07-13"
  s.description = "Use this gem if you want a simple 'enum-like' cache for your models that does not restrict updates, but will stay current with them."
  s.email = "olek@woodenbits.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/prosto_cache.rb",
    "prosto_cache.gemspec",
    "spec/prosto_cache_spec.rb",
    "spec/spec_helper.rb",
    "vendor/cache/diff-lcs-1.1.2.gem",
    "vendor/cache/git-1.2.5.gem",
    "vendor/cache/hashie-1.0.0.gem",
    "vendor/cache/jeweler-1.6.0.gem",
    "vendor/cache/rake-0.8.7.gem",
    "vendor/cache/rcov-0.9.9.gem",
    "vendor/cache/reek-1.2.8.gem",
    "vendor/cache/roodi-2.1.0.gem",
    "vendor/cache/rspec-2.3.0.gem",
    "vendor/cache/rspec-core-2.3.1.gem",
    "vendor/cache/rspec-expectations-2.3.0.gem",
    "vendor/cache/rspec-mocks-2.3.0.gem",
    "vendor/cache/ruby2ruby-1.2.5.gem",
    "vendor/cache/ruby_parser-2.0.6.gem",
    "vendor/cache/sexp_processor-3.0.5.gem",
    "vendor/cache/yard-0.6.8.gem"
  ]
  s.homepage = "http://github.com/olek/prosto_cache"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Very simple caching for your ActiveRecord models."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hashie>, [">= 1.0.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<reek>, ["~> 1.2.8"])
      s.add_development_dependency(%q<roodi>, ["~> 2.1.0"])
      s.add_development_dependency(%q<rake>, ["= 0.8.7"])
    else
      s.add_dependency(%q<hashie>, [">= 1.0.0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<reek>, ["~> 1.2.8"])
      s.add_dependency(%q<roodi>, ["~> 2.1.0"])
      s.add_dependency(%q<rake>, ["= 0.8.7"])
    end
  else
    s.add_dependency(%q<hashie>, [">= 1.0.0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<reek>, ["~> 1.2.8"])
    s.add_dependency(%q<roodi>, ["~> 2.1.0"])
    s.add_dependency(%q<rake>, ["= 0.8.7"])
  end
end

